// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.UserStore`7.CreateAsync(`0,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Identity.IdentityResult}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.UserStore`7.CreateError(System.Exception)~Microsoft.AspNetCore.Identity.IdentityResult")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.RoleStore`2.AddClaimsAsync(`0,System.Collections.Generic.IEnumerable{System.Security.Claims.Claim},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.RoleStore`2.CreateAsync(`0,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Identity.IdentityResult}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.RoleStore`2.CreateError(System.Exception)~Microsoft.AspNetCore.Identity.IdentityResult")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.RoleStore`2.RemoveClaimsAsync(`0,System.Collections.Generic.IEnumerable{System.Security.Claims.Claim},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.RoleStore`2.UpdateAsync(`0,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Identity.IdentityResult}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.UserStore`7.AddClaimsAsync(`0,System.Collections.Generic.IEnumerable{System.Security.Claims.Claim},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.UserStore`7.AddLoginAsync(`0,Microsoft.AspNetCore.Identity.UserLoginInfo,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.UserStore`7.AddToRoleAsync(`0,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.UserStore`7.AddUserTokenAsync(`5)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.UserStore`7.CreateAsync(`0,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Identity.IdentityResult}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.UserStore`7.RemoveClaimsAsync(`0,System.Collections.Generic.IEnumerable{System.Security.Claims.Claim},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.UserStore`7.RemoveFromRoleAsync(`0,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.UserStore`7.RemoveLoginAsync(`0,System.String,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.UserStore`7.RemoveUserTokenAsync(`5)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dgraph4Net.Identity.UserStore`7.UpdateAsync(`0,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Identity.IdentityResult}")]
