# This is a basic workflow to help you get started with Actions

name: Package Publisher

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Publish Dgraph4Net.Core package
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Dgraph4Net.Core/Dgraph4Net.Core.csproj
          PACKAGE_NAME: Dgraph4Net.Core
          NUGET_KEY: ${{ secrets.NugetKey }}

      - name: Publish Dgraph4Net package
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Dgraph4Net/Dgraph4Net.csproj
          PACKAGE_NAME: Dgraph4Net
          NUGET_KEY: ${{ secrets.NugetKey }}

      - name: Publish Dgraph4Net.Identity.Core package
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Dgraph4Net.Identity.Core/Dgraph4Net.Identity.Core.csproj
          PACKAGE_NAME: Dgraph4Net.Identity.Core
          NUGET_KEY: ${{ secrets.NugetKey }}

      - name: Publish Dgraph4Net.Identity package
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Dgraph4Net.Identity/Dgraph4Net.Identity.csproj
          PACKAGE_NAME: Dgraph4Net.Identity
          NUGET_KEY: ${{ secrets.NugetKey }}
