# This is a basic workflow to help you get started with Actions

name: Package Publisher

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build Projects
    runs-on: ubuntu-latest
    
    permissions:
      actions: read
      contents: read
      security-events: write
      pull-requests: write
      issues: write
      repository-projects: write

    services:
      dgraph:
        image: dgraph/standalone
        ports:
          - 8080:8080
          - 9080:9080
        options: --name dgraph --health-cmd "curl -f http://localhost:8080/health || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Build and Test
      env:
        GRPC_DNS_RESOLVER: native
      run: |
        dotnet restore src/Dgraph4Net.Core/Dgraph4Net.Core.csproj &&
        dotnet restore src/Dgraph4Net/Dgraph4Net.csproj &&
        dotnet restore src/Dgraph4Net.System.Text.Json/Dgraph4Net.System.Text.Json.csproj &&
        dotnet restore src/Dgraph4Net.Newtonsoft.Json/Dgraph4Net.Newtonsoft.Json.csproj &&
        dotnet restore tests/Dgraph4Net.Tests/Dgraph4Net.Tests.csproj &&
        dotnet restore tests/Dgraph4Net.Tests.System/Dgraph4Net.Tests.System.csproj &&
        dotnet build src/Dgraph4Net.Core/Dgraph4Net.Core.csproj --no-restore &&
        dotnet build src/Dgraph4Net/Dgraph4Net.csproj --no-restore &&
        dotnet build src/Dgraph4Net.System.Text.Json/Dgraph4Net.System.Text.Json.csproj --no-restore &&
        dotnet build src/Dgraph4Net.Newtonsoft.Json/Dgraph4Net.Newtonsoft.Json.csproj --no-restore &&
        dotnet build tests/Dgraph4Net.Tests/Dgraph4Net.Tests.csproj --no-restore &&
        dotnet build tests/Dgraph4Net.Tests.System/Dgraph4Net.Tests.System.csproj --no-restore &&
        dotnet test tests/Dgraph4Net.Tests/Dgraph4Net.Tests.csproj --no-build --no-restore &&
        dotnet test tests/Dgraph4Net.Tests.System/Dgraph4Net.Tests.System.csproj --no-build --no-restore
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"

  dependabot:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.actor == 'dependabot[bot]' &&  github.event_name == 'pull_request' && github.ref != 'refs/heads/master' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  pr-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/dependabot/master' }}
    needs: build
    # create a pr to master
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set Up current git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create PR with master
        run: |
          [ -z $(gh pr list -s open -S "dependabot changes" -L 1 --json number | grep "number") ] && gh pr create --title "dependabot changes" --body "Merging from dependabot"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  # This workflow contains a single job called "build"
  publish:
    needs: build
    name: Create Packages
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Build Packages
      run: |
        dotnet build -c Release ./src/Dgraph4Net.Core/Dgraph4Net.Core.csproj &&
        dotnet build -c Release ./src/Dgraph4Net/Dgraph4Net.csproj &&
        dotnet build -c Release ./src/Dgraph4Net.System.Text.Json/Dgraph4Net.System.Text.Json.csproj &&
        dotnet build -c Release ./src/Dgraph4Net.Newtonsoft.Json/Dgraph4Net.Newtonsoft.Json.csproj &&
        dotnet build -c Release ./tools/Dgraph4Net.Tools/Dgraph4Net.Tools.csproj &&
        dotnet pack -c Release -o ./build-packages -p:IncludeSymbols=false ./src/Dgraph4Net.Core/Dgraph4Net.Core.csproj &&
        dotnet pack -c Release -o ./build-packages -p:IncludeSymbols=false ./src/Dgraph4Net/Dgraph4Net.csproj &&
        dotnet pack -c Release -o ./build-packages -p:IncludeSymbols=false ./src/Dgraph4Net.System.Text.Json/Dgraph4Net.System.Text.Json.csproj &&
        dotnet pack -c Release -o ./build-packages -p:IncludeSymbols=false ./src/Dgraph4Net.Newtonsoft.Json/Dgraph4Net.Newtonsoft.Json.csproj &&
        dotnet pack -c Release -o ./build-packages -p:IncludeSymbols=false ./tools/Dgraph4Net.Tools/Dgraph4Net.Tools.csproj

    - name: Publish
      run: dotnet nuget push ./build-packages/*.nupkg --api-key ${{ secrets.NUGETKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
