# This is a basic workflow to help you get started with Actions

name: Package Publisher

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    name: Create Packages
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Source
      uses: actions/checkout@v2
    
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore dependencies
      run: dotnet restore src/Dgraph4Net.Core/Dgraph4Net.Core.csproj
      working-directory: ${{env.working-directory}}
      
    - run: dotnet restore src/DGraph4Net/DGraph4Net.csproj
      working-directory: ${{env.working-directory}}
      
    - run: dotnet restore src/Dgraph4Net.Identity.Core/Dgraph4Net.Identity.Core.csproj
      working-directory: ${{env.working-directory}}
      
    - run: dotnet restore src/DGraph4Net.Identity/DGraph4Net.Identity.csproj
      working-directory: ${{env.working-directory}}
    
    - name: Build projects
      run: dotnet build -c Release --no-restore src/Dgraph4Net.Core/Dgraph4Net.Core.csproj
      working-directory: ${{env.working-directory}}
      
    - run: dotnet build -c Release --no-restore DGraph4Net.csproj
      working-directory: ${{env.working-directory}}/src/DGraph4Net/
      
    - run: dotnet build -c Release --no-restore src/Dgraph4Net.Identity.Core/Dgraph4Net.Identity.Core.csproj
      working-directory: ${{env.working-directory}}
      
    - run: dotnet build -c Release --no-restore src/DGraph4Net.Identity/DGraph4Net.Identity.csproj
      working-directory: ${{env.working-directory}}
    
    - name: Generate Packages
      run: dotnet pack -c Release --no-build -o /tmp/build-packages -p:IncludeSymbols=false src/Dgraph4Net.Core/Dgraph4Net.Core.csproj
      working-directory: ${{env.working-directory}}
    
    - run: dotnet pack -c Release --no-build -o /tmp/build-packages -p:IncludeSymbols=false src/DGraph4Net/DGraph4Net.csproj
      working-directory: ${{env.working-directory}}
    
    - run: dotnet pack -c Release --no-build -o /tmp/build-packages -p:IncludeSymbols=false src/Dgraph4Net.Identity.Core/Dgraph4Net.Identity.Core.csproj
      working-directory: ${{env.working-directory}}
    
    - run: dotnet pack -c Release --no-build -o /tmp/build-packages -p:IncludeSymbols=false src/DGraph4Net.Identity/DGraph4Net.Identity.csproj
      working-directory: ${{env.working-directory}}
      
    - name: Publish Packages
      run: dotnet nuget push "/tmp/build-packages/Dgraph4Net.Core.`sed -n -e 's/\(.*\)<[Vv]ersion>\(.*\)<\/[Vv]ersion>\(.*\)/\2/p' src/Dgraph4Net.Core/Dgraph4Net.Core.csproj`.nupkg" -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json --skip-duplicate

    - run: dotnet nuget push "/tmp/build-packages/Dgraph4Net.`sed -n -e 's/\(.*\)<[Vv]ersion>\(.*\)<\/[Vv]ersion>\(.*\)/\2/p' src/DGraph4Net/DGraph4Net.csproj`.nupkg" -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json --skip-duplicate
    
    - run: dotnet nuget push "/tmp/build-packages/Dgraph4Net.Identity.Core.`sed -n -e 's/\(.*\)<[Vv]ersion>\(.*\)<\/[Vv]ersion>\(.*\)/\2/p' src/Dgraph4Net.Identity.Core/Dgraph4Net.Identity.Core.csproj`.nupkg" -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json --skip-duplicate
    
    - run: dotnet nuget push "/tmp/build-packages/Dgraph4Net.Identity.`sed -n -e 's/\(.*\)<[Vv]ersion>\(.*\)<\/[Vv]ersion>\(.*\)/\2/p' src/DGraph4Net.Identity/DGraph4Net.Identity.csproj`.nupkg" -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json --skip-duplicate
